[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyTitle("Yapped-Rune-Bear")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("Yapped-Rune-Bear")]
[assembly: AssemblyCopyright("Copyright ©  2022")]
[assembly: AssemblyTrademark("")]
[assembly: ComVisible(false)]
[assembly: Guid("aa6f0459-85a4-4e41-a6f3-08c611ffbcc0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
