[assembly: AssemblyVersion("2.2.4.0")]
[assembly: AssemblyTitle("Yapped-Rune-Bear")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("MadProbe, vawser & JKAnderson")]
[assembly: AssemblyProduct("Yapped-Rune-Bear")]
[assembly: AssemblyCopyright("Copyright © MadProbe 2023")]
[assembly: AssemblyTrademark("")]
[assembly: ComVisible(false)]
[assembly: Guid("aa6f0459-85a4-4e41-a6f3-08c611ffbcc0")]
[assembly: AssemblyFileVersion("2.2.4.0")]
